[package]
name = "nix-store-veritysetup-generator"
version = "1.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
uuid = "1.24.0"
log = { version = "0.4.34", features = ["alloc"] }

[dev-dependencies]
expect-test = "1.5.1"

[profile.release]
opt-level = "s"
panic = "abort"
lto = true
strip = true
