name: "Run nix flake check"

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  build:
    # Use an older ubuntu because starting with 24.04, unprivileged
    # user namespaces are forbidden via apparmor. The repart builder, however
    # relies on these.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - uses: samueldr/lix-gha-installer-action@v2026-06-15
      - run: nix flake check --log-format raw-with-logs -L

env:
  FORCE_COLOR: 1
